# docker-compose.yaml

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./server-flask:/app/server
    environment:
      - FLASK_ENV=development