version: "3.9"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    volumes:
      - ./server:/app/server
    environment:
      - FLASK_ENV=development